### PR TITLE
Fix/save var

### PR DESCRIPTION
**Pull request by dieris**
Assume the structure: `data[chan]['data']['Data']` and `data[chan]['data']['Variance']`. Not sure if this was the intent. Sorry for all these commits, they were generated when rebasing from master.

### CODE REVIEW

**Comment by blakejohnson** [comment]
I will try rebasing this.

**Comment by blakejohnson** [comment]
Diego, can you check that I kept the import pieces? On this branch, try:
```
git fetch
git reset --hard origin/fix/save-var
```

**Comment by dieris** [comment]
the new commits are there, but there are several commits missing from master

**Comment by dieris** [comment]
did you mean to merge this into master?

**Comment by blakejohnson** [comment]
I just additionally merged it into master.

**Pull request merged**
