### PR TITLE
CLEAR pulse calibration

### PR DESCRIPTION
**Pull request by dieris**
As precarious as https://github.com/BBN-Q/Auspex/pull/67 until tested

### CODE REVIEW

**Comment by grahamrow** [comment]
Time for a rebase and testing?

**Comment by grahamrow** [comment]
Shouldn't alter anything else, want to give it a merge?

**Comment by dieris** [comment]
Yeah, I was thinking the same. Not tested yet, but it shouldn't harm to merge :) Getting there soon, so that I can finish up plots (for this and DRAG)

**Comment by dieris** [comment]
Actually I managed to break the fits with this, fixing it right now 😞

**Pull request merged**
