### PR TITLE
Tests - exp factory

### PR DESCRIPTION
**Pull request by dieris**
Restore some tests for `QubitExpFactory`

### CODE REVIEW

**Comment by dieris** [comment]
Only loading the correct `cfg_file` when the tests are run individually, not with `unittest discover`. It must be an import issue

**Comment by dieris** [comment]
Maybe there is a reason why these tests were disabled and switching between config files in QGL is still not allowed? :) @grahamrow @dellard Once `QGL.config` is imported with the default config file (by another test, for example), then it's too late to change it. Should we run the tests in a specific order? How do we make sure that `test_qubitexpfactory` loads the correct `test_QGL_config.json` for QGL?

**Comment by dieris** [comment]
I guess we can just add something like:

```ruby
import qgl_config_loc
cfg_QGL_file = './test_QGL_config.json'
qgl_config_loc.config(cfg_QGL_file)
import QGL.config
```

to `__init__` in the `test` folder. I'll try that.

**Comment by grahamrow** [comment]
It's hard to change things once the config files are loaded. This is true in both QGL and auspex since they try to do things for you automatically, and since python doesn't allow things to be reimported it's even worse trying to switch QGL config files from within auspex (this is the main reason why unit tests are hard). Dan and I talked about running the tests as subprocesses as a temporary kludge. One of the only legit fixes would be to require the user to manually instantiate the channel library in QGL instead of automagically doing it at import time.

**Comment by dellard** [comment]
The basic problem is what Graham described: if you have executable code (other than the usual definition of symbols) with side effects in an import, it's hard to ferret out all the effects.  It's probably possible to hack the importer to tell it to re-import things, but the only way to guarantee that no obscure side effects slipped by is to start a new Python process.


-Dan


Daniel Ellard

Senior Scientist, Network Research

Raytheon BBN Technologies

dan.ellard@raytheon.com

617-873-8004 (office)

________________________________

**Comment by dieris** [comment]
Ok, I see, I'll give it a shot with subprocesses. Closing this PR for now

**Comment by dieris** [comment]
Except that running the tests as subprocesses breaks the coverage... 😩

**Pull request closed without merging**
