### PR TITLE
Plot calibration points

### PR DESCRIPTION
**Pull request by dieris**
Not sure what's the best way to do this. Here I'm mocking up an axis for
the cal. points similar to what we did in matlab

### CODE REVIEW

**Comment by grahamrow** [comment]
I was wondering if we couldn't do something more advanced and, e.g., plot labeled vertical lines for the different cal values. Is this too much?

**Comment by dieris** [comment]
that's a cool idea. I guess the x-axis will still be bogus, though. Or is there a way to suppress ticks and values for the cals?

**Comment by grahamrow** [comment]
oops, I meant horizontal lines... such that the data could be visually referenced to them

**Comment by dieris** [comment]
I prefer vertical lines :) The problem with horizontal line is that there are usually multiple calibration points per qubit, 1) for redundancy 2) for different multi-qubit computational states. So I think the plot would be too cluttered

**Comment by grahamrow** [comment]
Okay, I'm sold on vertical lines for partitioning, possibly adding text labels along the horizontal axis. We can revisit that later, and I'll merge these changes for the time being.

**Pull request merged**
