### PR TITLE
Correlator node needs a pipeline manager

### PR DESCRIPTION
**Pull request by matthewware**
The correlator node doesn't inherit the pipelineMgr in the current code base.  How did this ever work?

### CODE REVIEW

**Comment by dieris** [comment]
it should get the global `__current_pipeline__` at node creation:
https://github.com/BBN-Q/bbndb/blob/11e5147b322dcc0e804682856c09a0022d511d10/bbndb/auspex.py#L81-L85

**Comment by matthewware** [comment]
@dieris I know!   Somehow this is not the case for me

**Comment by matthewware** [comment]
```python
pl = PipelineManager()
pl.create_default_pipeline()
pl.show_pipeline()
...
pl.add_correlator(pl['q2']["Demodulate"]["Integrate"], pl['q3']["Demodulate"]["Integrate"])

pl['q2']["Demodulate"]["Integrate"]["Average"].add(Write(label='var'), connector_out='final_variance')
pl['q3']["Demodulate"]["Integrate"]["Average"].add(Write(label='var'), connector_out='final_variance')

pl['q2']["Demodulate"]["Integrate"]["Average"]["var"].groupname = 'q2-main'
pl['q2']["Demodulate"]["Integrate"]["Average"]["var"].datasetname = 'variance'

pl['q3']["Demodulate"]["Integrate"]["Average"]["var"].groupname = 'q3-main'
pl['q3']["Demodulate"]["Integrate"]["Average"]["var"].datasetname = 'variance'

python> pl['q2']["Demodulate"]["Integrate"].__dict__
'_sa_instance_state': <sqlalchemy.orm.state.InstanceState at 0x1a2a7e9450>,
 'pipelineMgr': <auspex.qubit.pipeline.PipelineManager at 0x1a2a36a8d0>,
 'box_car_stop': 1e-07,
 'hash_val': 4162503134,
 'qubit_name': 'q2',
 'label': None,
 'bias': 0.0,
 'simple_kernel': True,
 'node_type': 'integrate',
 'demod_frequency': 0.0,
 'id': 2,
 'box_car_start': 0.0,
 'kernel': None}

python>pl['q2']["Demodulate"]["Integrate"]["Correlate"].__dict__
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState at 0x1a2a879610>,
 'node_type': 'correlate',
 'hash_val': 1335436607,
 'qubit_name': 'q2-q3',
 'label': 'Correlate q2q3',
 'pipelineMgr': none}
```

This was the case with integrated and demodulated streams.

**Comment by matthewware** [comment]
So when you did:
```python
pl['q2']["Demodulate"]["Integrate"]["Correlate"].add(Average(label='test_corr_avg')).add(Display(label='test_corr_avg',plot_dims=0))

~/Github/Auspex/src/auspex/qubit/pipeline.py in __getitem__(self, key)
    418 
    419     def __getitem__(self, key):
--> 420         return self.get_stream_selector(key)

~/Github/Auspex/src/auspex/qubit/pipeline.py in get_stream_selector(self, pipeline_name)
    190             return sel_labels[0]
    191         else:
--> 192             raise Exception(f"Name {pipeline_name} does not specify a pipeline. If there are multiple pipelines for a qubit you must specify 'qubit_name pipeline_name'")
    193         return sel_by_name[pipeline_name]
    194 

Exception: Name q2 does not specify a pipeline. If there are multiple pipelines for a qubit you must specify 'qubit_name pipeline_name'

**Comment by matthewware** [comment]
@grahamrow This PR along with the PR in bbndb is working for me.  I also ran the failing CI test locally and they are working.

**Pull request merged**
