### PR TITLE
Feature/plotting-for-fits

### PR DESCRIPTION
**Pull request by matthewware**
Added plotting and fit features to Auspex for qubit experiments.

### CODE REVIEW

**Comment by matthewware** [comment]
@grahamrow, @gribeill, @dieris what do you guys think?

**Comment by dieris** [comment]
On a first pass they look good to me. What is not clear to me is their intended use. Is it for a same-notebook data analysis as an alternative to Qlab.jl? Or for pulse calibration? If for the latter, how are they different from the plots in pulse_calibration.py?

**Comment by dieris** [comment]
Nvm, I see they're expanding on them. Still, is the showPlot flag intendend for post-acquisition data analysis? And thanks for the fit tests!

**Comment by matthewware** [comment]
They're just basic analysis plots like we have in Qlab.jl.  Seems like we should have a set in Auspex so our devoted users can do basic analysis without having to setup Julia as well.  I think we should keep using the fit functions in Qlab.jl in general though.

**Comment by matthewware** [comment]
If there are no more comments I'll merge in the morning.

**Comment by gribeill** [comment]
Sorry, finally getting to this... this all looks good, I think?

I'm starting to think we might want to think about a cleaner way to split base auspex from the qubit-specific parts? I don't know what this might look like but probably worth pondering...

**Pull request merged**
